//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhu.Footprint.Web.UI.Apps.Footprint {
    
    
    public partial class MultipointRegionModal {
        
        /// <summary>
        /// multipointRegionModal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Jhu.Graywulf.Web.UI.Controls.Form multipointRegionModal;
        
        /// <summary>
        /// multipointRegionName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox multipointRegionName;
        
        /// <summary>
        /// multipointRegionNameFormatValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator multipointRegionNameFormatValidator;
        
        /// <summary>
        /// multipointRegionPoly control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton multipointRegionPoly;
        
        /// <summary>
        /// multipointRegionCHull control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton multipointRegionCHull;
        
        /// <summary>
        /// multipointRegionCoordinates control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox multipointRegionCoordinates;
    }
}
